CREATE TABLE `user` (
	`id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `loginId` VARCHAR(16) NOT NULL,
    `password` CHAR(64) NOT NULL,
    `email` VARCHAR(64) NOT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `name` (
	`id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`userId` BIGINT NOT NULL,
    `name` VARCHAR(32) NOT NULL,
    `isMain` BOOLEAN NOT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `attend` (
	`id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`nameId` BIGINT NOT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `hall` (
	`id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`userId` BIGINT NOT NULL,
    `name` VARCHAR(32) NOt NULL,
    `hp` BIGINT NOT NULL,
    `contents` TEXT NOT NULL,
    `imagePath` VARCHAR(128) NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `hp` (
	`id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`nameId` BIGINT NOT NULL,
    `point` BIGINT NOT NULL,
    `game` VARCHAR(32) NOT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `dicehistory` (
	`id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`game` BIGINT NOT NULL,
    `result` BOOLEAN NOT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `dicehall` (
	`id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`gameId` BIGINT NOT NULL,
    `nameId` BIGINT NOT NULL,
    `result` BOOLEAN NOt NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `dicebuffer` (
	`id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`nameId` BIGINT NOT NULL,
    `hp` BIGINT NOt NULL,
    `result` BOOLEAN NOT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `boxhistory` (
	`id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`game` BIGINT NOT NULL,
    `result1` TEXT NOT NULL,
    `result2` TEXT NOT NULL,
    `result3` TEXT NOT NULL,
    `result4` TEXT NOT NULL,
    `result5` TEXT NOT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `boxhall` (
	`id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`gameId` BIGINT NOT NULL,
    `nameId` BIGINT NOT NULL,
    `result` BIGINT NOT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `boxbuffer` (
	`id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`nameId` BIGINT NOT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `lottohistory` (
	`id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`game` BIGINT NOT NULL,
    `lotto` TEXT NOT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `lottohall` (
	`id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`gameId` BIGINT NOT NULL,
    `nameId` BIGINT NOT NULL,
    `result` INT NOT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `lottobuffer` (
	`id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`nameId` BIGINT NOT NULL,
    `lotto` TEXT NOT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SELECT * FROM `lottobuffer`;
SELECT * FROM `lottohistory`;
SELECT * FROM `lottohall`;

SELECT * FROM `boxbuffer`;
SELECT * FROM `boxhistory`;
SELECT * FROM `boxhall`;

SELECT * FROM `dicebuffer`;
SELECT * FROM `dicehistory`;
SELECT * FROM `dicehall`;

SELECT * FROM `user`;
SELECT * FROM `name`;
SELECT * FROM `hp`;


INSERT INTO `hp`
(`nameId`, `point`, `game`)
VALUE
(6, 100000, 'Test');


